KBCrossFIT/FE

Users/student/Desktop/final project 초안/FE-dev/src/components/Header.vue
Users/student/Desktop/final project 초안/FE-dev/src/dummydata.js
Users/student/Desktop/final project 초안/FE-dev/src/views/account/auth/Find.vue
Users/student/Desktop/final project 초안/FE-dev/src/views/account/auth/Login.vue

9/20 로그인 기능 추가

---

src/components/Header.vue
src/views/account/auth/Login.vue
src/views/account/profile/DeleteAccount.vue
src/views/home/DevBtn.vue
src/views/investmentTest/InvestmentTestStart.vue

feat: 계정 삭제시 현재 로그인 한 사용자 비밀번호 받아서 확인.

0920 kangmin 계정 삭제 유저 비밀번호 체크기능

---

src/views/portfolio/MyPortfolio.vue
src/views/portfolio/Portfolio.vue
src/views/portfolio/ProductComparison.vue

feat: 상품 비교 페이지 보완
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
상품 수익률 비교 막대그래프 추가.
상품 비교 최대 3개/ 같은 종목만 가능하도록 제한.
일괄 비우기 버튼 추가.
그래프 아래 상품별 상세 정보 표시 추가.

0925 Kangmin 상품 비교 페이지 보완

---

src/api/financeApi.js
src/store/index.js
src/store/modules/bond.js
src/store/modules/deposit.js
src/store/modules/fund.js
src/store/modules/saving.js
src/views/financialProducts/BondListView.vue
src/views/financialProducts/DepositListView.vue
src/views/financialProducts/FundListView.vue
src/views/financialProducts/SavingListView.vue

1. 펀드 검색 기능 추가(검색 모드, 리스트 모드로 나누어 기능 구현)

feat: 펀드 검색 기능 추가

---

src/components/Modal/ModalTest.vue
src/components/sideBar/SidebarMenu2.vue
src/components/sideBar/SidebarMenu3.vue
src/views/account/auth/SignUp.vue
src/views/investmentTest/InvestmentTest.vue

feat: 회원가입 투자성향분석 에러 수정.
사이드바-장바구니 디자인/버튼 추가
투자성향분석 - 진행도 추가.

0928 Kangmin 투자성향분석/사이드바 장바구니/회원가입 모달

---

src/components/sideBar/SidebarMenu1.vue
src/components/sideBar/SidebarMenu2.vue
src/components/sideBar/SidebarMenu3.vue
src/views/insight/Influencer.vue
src/views/insight/Influencer_title.vue
src/views/insight/News.vue
src/views/insight/News_title.vue
src/views/insight/Youtube.vue

design: 인사이트 인플루언서+뉴스 페이지 디자인 수정.

0928 Kangmin 인사이트 페이지 디자인 수정

---

src/components/Header.vue
src/components/sideBar/SidebarMenu1.vue
src/components/sideBar/SidebarMenu2.vue
src/router/index.js
src/views/financialProducts/FinancialProducts.vue
src/views/financialProducts/ProductDesc.vue
src/views/insight/Influencer_title.vue
src/views/insight/News_title.vue
src/views/insight/Youtube.vue
src/views/insight/Youtube_title.vue

feat: 사이드바의 내 포트폴리오, 장바구니 상품들이 9개 이상일 경우 숫자 대신 ...으로 출력되도록 함.

0928 Kangmin 사이드바 상품 9개 이상 시 ...으로 출력.

---

src/api/memberApi.js
src/router/index.js
src/views/account/auth/Login.vue
src/views/account/auth/SignUp.vue

코드들이 살짝 틀렸어서 다시 올립니다. 그래도 작동 안되니 백엔드쪽이랑 상의해서 수정해야할것 같습니다.

회원가입 및 로그인

---

src/router/index.js
src/views/cart/CartItem.vue

1. 장바구니 기능 FE/BE 연동(http://localhost:5173/cartItem)

feat: 장바구니 CRUD BE 연동

---

src/views/account/auth/SignUp.vue

디자인 부분만 바꾸면 될것 같습니다. Header도 script 코드가 바뀌였습니다.

로그인 및 회원가입

---

src/router/index.js
src/views/account/auth/Login.vue
src/views/cart/CartItem.vue
src/views/portfolio/PortfolioData.vue
src/views/recentView/recentView.vue

* 포트폴리오 CRUD 기능 연동(http://localhost:5173/portfolio-data)

feat: 포트폴리오 CRUD BE 연동

---

src/store/modules/saving.js
src/views/account/auth/Login.vue
src/views/financialProducts/Cart.vue
src/views/financialProducts/ProductDesc.vue

성준님 회원가입 페이지 열리지 않아 확인용 커밋.
로그인 페이지 입력박스 잘 안보여서 템플릿/디자인 수정해 놓았습니다.

1003 FinanceApi SearchSaving

---

src/api/personaApi.js
src/store/index.js
src/store/modules/persona.js
src/views/insight/Influencer_title.vue

인플루언서 페이지 제목,직업 db저장된 값으로 보여지게 연동했습니다.

feat: 인플루언서제목 db리스트호출 기능

---

src/api/financeApi.js
src/components/Header.vue
src/router/index.js
src/store/modules/bond.js
src/store/modules/fund.js
src/views/account/auth/SignUp.vue
src/views/financialProducts/FinancialProducts.vue
src/views/financialProducts/ProductDesc.vue

feat: 상품 리스트 페이지, 상품 상세 페이지
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
헤더 상품리스트 주소 변경 (header.vue, router/index.js).
상품리스트 페이지네이션, 주식 탭 추가. (FinancialProducts.vue).
상품 상세 해당 id 데이터 불러오기(ProductDesc.vue).

1007 Fekangmin 상품 리스트 페이지, 상품 상세

---

src/api/hit.js
src/main.js
src/store/hitStore.js
src/views/financialProducts/FinancialProducts.vue

1. FE 조회수 증가 기능 구현
2. 조회수 증가 기능 FE, BE 연동

feat: FE 조회수 증가 기능 구현 및  BE, FE 연동

---

src/views/home/ProductList.vue

1. 사용자 로그인 후 사용자에 맞는 연령대별 추천 상품 및 투자성향별 추천 상품 출력 기능 추가

feat: 사용자 로그인 후 사용자에 맞는 상품 리스트 출력 기능 추가

---

src/router/index.js
src/views/financialProducts/FinancialProducts.vue
src/views/portfolio/ProductComparison.vue
src/views/stock/StockList.vue
src/views/stock/StockSearch.vue

design: 금융상품 리스트, 주식 리스트/ 검색 디자인 수정.
fix : router/index.js
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

1008 kangmin design: 금융상품 리스트, 주식 디자인 수정.

---

src/api/cartApi.js
src/components/Modal/ModalStock.vue
src/router/index.js
src/store/modules/cart.js
src/views/portfolio/MakePortfolio.vue

포트폴리오 store 문제 해결

---

src/views/financialProducts/FinancialProducts.vue

fix:FinancialProducts 검색 백엔드 연동.

1009 kangmi fix:FinancialProducts 검색 백엔드 연동.

---

src/components/Modal/ModalStock.vue
src/views/financialProducts/FinancialProducts.vue
src/views/portfolio/MakePortfolio.vue
src/views/stock/StockList.vue

feat : 포트폴리오 구성 - 주식 모달 창 연결
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
ModalStock.vue
주식 데이터 fetch해와서 리스트로 표시.
상단 리스트에서 주식 선택 후,
하단 리스트에서 주식의 수 결정 한 뒤에 구성페이지로 보냅니다.
MakePortfolio.vue
구성 주식의 경우 ModalStock에서 받아올 수 있도록 연결.
전체 디자인 수정, 
FinancialProducts.vue
상품명 분류 태그 통일(bonds -> bond, funds -> fund).

1009 kangmin feat: 포트폴리오 구성페이지 모달주식 연결

---

src/api/chatbot.js
src/components/Modal/ModalPersona.vue
src/components/Modal/ModalTest.vue
src/components/persona/Persona_avatar_image.vue
src/views/insight/Influencer.vue
src/views/insight/Influencer_title.vue

feat: 페르소나 챗봇 기능 추가

---

src/api/hit.js
src/store/youtubeStore.js
src/views/home/ProductList.vue
src/views/insight/YoutubeDetail.vue
src/views/insight/YoutubeVideos.vue

1. 유튜브 상세페이지 이동 시 이전 값 가져오는 오류 해결

fix: 유튜브 상세페이지 오류 해결

---

src/views/home/ProductList.vue

1. 사용자 로그인 시 자신의 연령대 및 투자성향에 버튼이 로드 되지 않던 기능 오류 해결

fix: 사용자 로그인 시 자신의 연령대 및 투자성향에 버튼 로드 되도록 오류 수정

---

src/views/home/ProductList.vue

1. 사용자 로그인 시 금융 상품 출력 사용자 맞춤화 오류 해결

fix: 사용자의 연령 및 투자성향 받아와 activeAge 및 activePreference 활성화하도록 오류 해결

---

src/store/modules/deposit.js
src/store/modules/saving.js
src/views/home/ProductList.vue

1. 추천 상품 출력 안될 시 mysql table 생성 후 값 여러 개 넣어야 합니다. 연령별로 투자성향별로 다 다르게 작업하고 난 후 실행해야 출력되고 이동됩니다.

feat: 홈페이지 추천 상품 클릭 시 상세페이지로 이동 기능 추가

---

src/components/Modal/ModalCart.vue
src/components/Modal/ModalStock.vue
src/views/financialProducts/FinancialProducts.vue
src/views/portfolio/MakePortfolio.vue

feat : MakePortfolio.vue 페이지, ModalCart, ModalStock 구성.

feat: MakePortfolio.vue 페이지, ModalCart, ModalStock 구성.

---

src/views/investmentTest/InvestmentTestEnd.vue
src/views/investmentTest/InvestmentTestStart.vue
src/views/investmentTest/MyInvestmentAnalyze.vue

design: 투자성향 분석 시작/종료 문구 수정,
내투자성향, 포트폴리오 구성페이지 파이차트 5가지 성향에 맞춰 재설정.

design: 추천 투자 비율 수정, test시작페이지

---

package-lock.json
package.json
src/router/index.js
src/store/modules/cart.js
src/store/modules/saving.js
src/store/youtubeStore.js
src/views/cart/CartEx.vue
src/views/financialProducts/Cart.vue
src/views/insight/YoutubeDetail.vue
src/views/portfolio/MakePortfolio.vue
yarn.lock

1. 장바구니 금융 상품 선택 기능 추가
2. 포트폴리오 구성하기 버튼 기능 추가

feat: 장바구니 데이터 선택 기능 및  포트폴리오 구성하기 버튼 기능 추가

---

src/App.vue
src/components/DefaultLayout.vue
src/components/Header.vue
src/components/Sidebar.vue
src/components/sideBar/SidePanel.vue
src/memo2.vue
src/views/home/Carousel.vue
src/views/home/ComparisonSection.vue
src/views/home/Home.vue

메인페이지 등등 10/11

---

src/views/financialProducts/FinancialProducts.vue
src/views/home/ProductList.vue

design: 메인페이지 상품 리스트 버튼 디자인

---

src/views/home/ProductList.vue

1. 로그인되지 않은 사용자에겐 20대, '공격투자형' 고정

fix: 로그인되지 않은 사용자에게 추천 상품 기능 오류 해결

---

src/ProductLabel.js
src/views/financialProducts/Cart.vue
src/views/financialProducts/FinancialProducts.vue
src/views/financialProducts/ProductDesc.vue
src/views/investmentTest/InvestmentTest.vue
src/views/stock/StockList.vue
src/views/stock/StockSearch.vue

feat: 투자성향분석, 상품리스트, 주식 리스트, 장바구니
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
상품 리스트 페이지- 검색/ 검색창 지우기 버튼 동작.
주식 리스트 폰트 디자인 수정, 천단위 구분메서드 적용/ 
상품 상세 페이지 -배경색 수정
포트폴리오 구성페이지- 장바구니 항목들 표시데이터 몇가지 삭제
가져온 주식 삭제 버튼 복원
장바구니 페이지 -로그인 안한 상태로 진입 시 로그인 라우터 표시. 
로그인 한 상태로, 장바구니가 비어있다면 로그인 라우터 표시 안됨.

feat: 투자성향분석, 상품리스트, 주식 리스트, 장바구니

---

src/components/SortIndicator.vue
src/views/financialProducts/FinancialProducts.vue
src/views/investmentTest/InvestmentTest.vue
src/views/portfolio/ProductComparison.vue
src/views/stock/StockList.vue
src/views/stock/StockSearch.vue

김강민
-금융상품 페이지
은행 아이콘 추가 : 발행자 명 앞 아이콘 들어갈 영역 확보(구현중).
데이터 레이블 순서 : 완료
장바구니 들어있으면 하이라이트 :
정렬 : 해당 페이지에서만 가능한 상태(프론트에서 작동)
지우기 버튼 : 완료
지우기 -> 새로고침 : 각 항목들 검색 버튼 아이콘으로 대체.
장바구니 담을지 말지 알러트(최 후순위) : 완료
주식 페이지 네이버 증권과 연결(드랍다운 삭제)

Feat: 상품리스트 페이지 담당 기능, 디자인

---

src/views/financialProducts/Cart.vue
src/views/financialProducts/FinancialProducts.vue

1. 장바구니 리스트에서 상품 삭제 시 모든 상품 사라지는 오류 해결 하나씩 삭제 가능
2. 장바구니 리스트에서 삭제한 상품 금융 상품 리스트에서 언체크 되어 있게 동기화 문제 해결

fix: 장바구니 리스트에서 삭제 오류 해결

---

src/views/portfolio/MakePortfolio.vue

1. 포트폴리오 저장 시 백엔드에 요청 연동했습니다.
* 그래프 label 수정
* 이름 입력 ''일 경우 저장x, alert 출력
* 아이템 선택 x시, alert 출력

feat: 포트폴리오 저장 기능

---

src/store/youtubeStore.js
src/views/insight/YoutubeVideos.vue

1. 이달의 추천 영상 2개 출력 후 1개 안보이는 오류 해결

fix: 유튜브 영상 안보이는 오류 해결

---

src/views/insight/Influencer_title.vue
src/views/insight/News_title.vue

feat: news api기능

---

src/views/financialProducts/Cart.vue
src/views/insight/Influencer.vue
src/views/insight/News.vue
src/views/insight/Youtube.vue
src/views/insight/YoutubeVideos.vue

design: 인사이트 페이지 유튜브 및 왼쪽 사이드 디자인 수정

---

src/ProductLabel.js
src/components/Header.vue
src/views/financialProducts/FinancialProducts.vue
src/views/financialProducts/ProductDesc.vue
src/views/stock/StockList.vue
src/views/stock/StockSearch.vue

Design: 상품 리스트, 상품 상세, 주식 리스트/검색 페이지 디자인 수정

Design: 상품 리스트, 상품 상세, 주식 리스트/검색 페이지 디자인 수정

---

src/store/modules/portfolio.js
src/views/portfolio/MyPortfolio.vue
src/views/portfolio/Portfolio.vue

1. 포트폴리오 결과 페이지에서 리스트 이동 시 추가되어서 리스트 출력 안되는 오류 해결(비동기 방식 처리)

fix: 포트폴리오 생성 시 포트폴리오 리스트에 추가 출력 안되는 오류 해결

---

src/components/Header.vue
src/views/insight/News.vue
src/views/portfolio/MakePortfolio.vue

1. 동기화 오류 해결
2. makePortfolio 금액 바뀐 부분 수정

fix: 헤더 및 핀테인먼트 왼쪽 사이드바 동기화 문제 해결

---

src/components/Header.vue
src/views/financialProducts/FinancialProducts.vue
src/views/investmentTest/MyInvestmentAnalyze.vue
src/views/portfolio/MakePortfolio.vue
src/views/portfolio/ProductComparison.vue

Design: 투자성향 분석 페이지, 상품 리스트
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
투자성향 분석 로그인 안했으면 로그인 창, 투자성향 분석 없으면 투자분석 이동 창 표시
차트 크기 조정
상품리스트 펀드의 위험도 텍스트 수정

Design: 투자성향 분석 페이지, 상품 리스트

---

src/components/Modal/ModalPersona.vue
src/components/persona/PersonaChart.vue
src/components/persona/PersonaComment.vue
src/views/financialProducts/Cart.vue
src/views/investmentTest/InvestmentTestStart.vue
src/views/investmentTest/MyInvestmentAnalyze.vue
src/views/portfolio/MakePortfolio.vue
src/views/portfolio/MyPortfolio.vue

나의 포트폴리오, 장바구니, 투자성향분석, 내 투자성향분석.

feat: 로그인 요구 

---

src/components/Header.vue
src/views/account/auth/SignUp.vue
src/views/financialProducts/Cart.vue
src/views/investmentTest/InvestmentTest.vue
src/views/portfolio/MakePortfolio.vue
src/views/portfolio/MyPortfolio.vue
src/views/stock/StockList.vue

주식 리스트 너비 조정(두줄 표시안되게)
회원가입/로그인 페이지 비밀번호 ****표시.
마이페이지 이동 클릭 이벤트 지워둠.
로그인 정보 요구 창 스타일 조정.

Design: 헤더, 주식 리스트, 

---

src/views/financialProducts/Cart.vue
src/views/investmentTest/InvestmentTestStart.vue
src/views/investmentTest/MyInvestmentAnalyze.vue
src/views/portfolio/MakePortfolio.vue
src/views/portfolio/MyPortfolio.vue

로그인했지만 장바구니가 비어 있을 때(cart.vue) 알림 스타일 수정.
나의 포트폴리오, 포트폴리오 만들기, 장바구니, 투자성향 분석 페이지들의 로그인 정보 없음 스타일 일치.

1104 Design: 로그인 정보 요구 스타일 수정

---

src/views/home/ProductList.vue

추천 금융 상품 마우스 hover 시 기본 커서가 아닌 pointer 커서로 변경

MVP-7 / fix : 추천 금융 상품 마우스 hover 시 pointer 변경

---

src/store/authStore.js
src/views/financialProducts/FinancialProducts.vue

앞선 문제와 마찬가지로 pinia 스토어에 로그인 유지 변수였던 isAuthenticated가 초기화 되면서 발생한 오류입니다.
로그인 여부는 변수로 체크하지 않고, isLoggedIn() 메서드를 만들어서 매번 jwt 토큰이 유효한지 체크를 하여 로그인 여부를 판별하게 하였습니다.

MVP-18/fix: 새로고침 시 로그인 풀림 에러 수정
